name: test-environment
channels:
  - conda-forge
dependencies:
  - defusedxml
  - rasterio
  - numpy
  - requests
  - eccodes
  - netcdf4
  - pandas
  - pytest
  - pytest-cov
  - pip
  - pip:
    - eccodes
